Implement full installation / reset button for module card
Delusoire/bespoke-modules pull request #4
Opened 2024-07-15 00:21 UTC by zhngharry

Adds a full installation / full uninstall button to the module card.

Maybe we should discuss what the best label for the button is? I have it as "Install" and "Reset" as of now, but I can change that if wanted, especially because Install overlaps with the Install State Transition, but I didn't know a better (one-word) alternative.

Looks like this:

![image](https://github.com/user-attachments/assets/a7e92763-0b1c-4d77-bbc1-d1c5180440ab)
![image](https://github.com/user-attachments/assets/a7fb4788-7e09-48bf-a0a8-360fbcddc710)

2024-07-15 22:28 UTC, Delusoire requested changes

2024-07-15 22:28 UTC, Delusoire commented on modules/marketplace/src/components/ModuleCard/index.tsx
>  	return (
I think this clears up the logic a bit more:

```suggestion
	const fastDelete = async () => {
		const module = moduleInstance.getModule();

		dis: if (moduleInstance.isEnabled()) {
			if (module.canDisable(moduleInstance)) {
				if (await module.disable()) {
					props.updateModule(module);
					break dis;
				}
			}
			return false;
		}

		del: if (moduleInstance.isInstalled()) {
			if (moduleInstance.canDelete()) {
				if (await moduleInstance.delete()) {
					props.updateModule(module);
					break del;
				}
			}
			return false;
		}

		rem: if (moduleInstance.isLocal()) {
			if (moduleInstance.canInstallRemove()) {
				if (await moduleInstance.remove()) {
					if (module.parent) {
						props.updateModule(module);
					} else {
						props.removeModule(module);
					}
					break rem;
				}
			}
			return false;
		}

		return true;
	};

	const fastInstall = async () => {
		let localModuleInstance = moduleInstance;
		let localModule = localModuleInstance.getModule();

		add: if (!moduleInstance.isLocal()) {
			if (moduleInstance.canAdd()) {
				localModuleInstance = await moduleInstance.add();
				if (localModuleInstance) {
					localModule = localModuleInstance.getModule();
					props.addModule(localModule);
					props.selectInstance(localModuleInstance);
					break add;
				}
			}
			return false;
		}

		ins: if (!localModuleInstance.isInstalled()) {
			if (localModuleInstance.canInstallRemove()) {
				if (await localModuleInstance.install()) {
					props.updateModule(localModule);
					break ins;
				}
			}
			return false;
		}

		ena: if (!localModuleInstance.isEnabled()) {
			if (localModule.canEnable(localModuleInstance)) {
				if (await localModule.enable(localModuleInstance)) {
					props.updateModule(localModule);
					break ena;
				}
			}
			return false;
		}

		return true;
	};

	const isInstalled = moduleInstance.isInstalled();

	const fastInstallDeleteButton = isInstalled ? (
		<>
			<MdDeleteSweep />
			Reset
		</>
	) : (
		<>
			<MdAddCircleOutline />
			Install
		</>
	);

	const footer = (
		<div className="flex justify-between w-full">
			{showLoaded && SettingsToggle && (
				<SettingsToggle
					className="x-settings-button justify-end"
					value={loaded}
					onSelected={onToggleLoaded}
				/>
			)}
			<button
				className={`cursor-pointer border-0 rounded inline-flex items-center justify-between ${
					isInstalled ? "bg-gray-500" : "bg-green-500"
				} text-white px-2 py-2 w-1/2 h-8`}
				onClick={async () => {
					if (isInstalled) {
						await fastDelete();
					} else {
						await fastInstall();
					}
				}}
			>
				{fastInstallDeleteButton}
			</button>
		</div>
	);

	return (
```

It'd also be great to rename the `{buttons}` (passed as a child to `<ModuleCardContent/>`) to `{footer}` or the code will break. But I wasn't able to include it in the suggestion.

2024-07-16 00:40 UTC, zhngharry commented on modules/marketplace/src/components/ModuleCard/index.tsx
>  	return (
Done 👍🏼

2024-07-16 01:29 UTC, Delusoire approved these changes

2024-07-16 01:30 UTC, merged

2024-07-16 01:34 UTC, Delusoire commented
Thank you for the contribution :)